# Generated by Django 6.0.1 on 2026-01-12 00:50

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuario_empresa'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', core.models.UsuarioManager()),
            ],
        ),
    ]
