# Generated by Django 4.2.14 on 2026-01-16 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_empresa_logomarca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logomarca',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('EXECUCAO', 'Em Execução'), ('AGUARDANDO_PECA', 'Aguardando Peça'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20),
        ),
    ]
