# Generated by Django 4.2.14 on 2026-01-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_empresa_logomarca_alter_ordemservico_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="plano_atualizado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="plano_periodo",
            field=models.CharField(
                choices=[("30d", "30 dias"), ("6m", "6 meses"), ("12m", "12 meses")],
                default="30d",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="plano_vencimento_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
