# Generated by Django 4.2.14 on 2026-01-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_empresa_plano_detalhes"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="is_ativo",
            field=models.BooleanField(default=True),
        ),
    ]
