# Generated by Django 4.2.14 on 2026-01-16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_funcionario_executor"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="data_ingresso",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
