# Generated by Django 4.2.14 on 2026-01-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_funcionario_data_ingresso"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FormaPagamento",
        ),
    ]
