# Generated by Django 4.2.14 on 2026-01-16

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_remove_formapagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="km",
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
